### ISSUE TITLE
ValueError: Specified \n as separator or delimiter. 

### ISSUE THREAD

**Issue by manivenkatesan** [betsig/how_are_we_stranded_here#10]
Hi betsig,
Thank you for making this cool tool. I've tried to run the following code:
`check_strandedness --gtf Homo_sapiens.GRCh38.106.gtf --transcripts Homo_sapiens.GRCh38.cdna.abinitio.fa --reads_1 r1.fastq.gz --reads_2 r2.fastq.gz`

I am using:
kallisto                  0.44.0     
python                    3.9.12
rseqc                     4.0.0   

The first processing steps are fine:
```
converting gtf to bed
using kallisto_index as kallisto index
creating fastq files with first 200000 reads
quantifying with kallisto

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 204,563
[index] number of k-mers: 116,332,896
[index] number of equivalence classes: 842,500
Warning: 60093 transcripts were defined in GTF file, but not in the index
[quant] running in paired-end mode
[quant] will process pair 1: r1.fq r2.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 200,000 reads, 189,766 reads pseudoaligned
[quant] estimated average fragment length: 185.825
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,009 rounds
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. done

checking strandedness
Reading reference gene model Homo_sapiens.GRCh38.106.bed ... Done
Loading SAM/BAM file ...  Total 200000 usable reads were sampled
```

But then I get the following error:
```
Traceback (most recent call last):
  File "/home/m.venkatesan/.conda/envs/strandedness/bin/check_strandedness", line 10, in <module>
    sys.exit(main())
  File "/home/m.venkatesan/.conda/envs/strandedness/lib/python3.9/site-packages/how_are_we_stranded_here/check_strandedness.py", line 185, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "/home/m.venkatesan/.conda/envs/strandedness/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/m.venkatesan/.conda/envs/strandedness/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "/home/m.venkatesan/.conda/envs/strandedness/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1537, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
```
I currently don't know what's going on and your help would be appreciated.

**Comment by XYCynthiaT** [comment]
I met the same situation, and it was perfectly solved when I switched from python 3.9 to python 3.6.

**Comment by dshinzie** [comment]
I was able resolve this by forking the library and change the line on line 185 to:

`result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\r\n", header=None)`

**Comment by betsig** [comment]
Fixed in https://github.com/betsig/how_are_we_stranded_here/commit/617b2166f460445f93c5678863df53b6ffc3b798

**Comment by Michael-Geuenich** [comment]
I've had this issue too, but fixed it by installing from github. Would it be possible to update the package so that it can also be installed via pip?
