### ISSUE TITLE
Anyone successfully get this library to work?

### ISSUE THREAD

**Issue by dshinzie** [betsig/how_are_we_stranded_here#12]
The same issue has been reported a few times and I was wondering if anyone has actually got this thing to work. It seems super useful so it would be nice to know if there is something we can do to help.

```
$  | Results stored in: stranded_test_B10_EXP_220130_C8_3_S8_L004_R1_001
$  | converting gtf to bed
$  | Checking if fasta headers and bed file transcript_ids match...
$  | Can't find transcript ids from GRCh38.fasta in stranded_test_B10_EXP_220130_C8_3_S8_L004_R1_001/GRCh38.bed
$  | Trying to converting fasta header format to match transcript ids to the BED file...
$  | Can't find any of the first 10 BED transcript_ids in fasta file... Check that these match
```

**Comment by betsig** [comment]
Hello,

Could you please give a full reproducible version of the commands and data you used that is giving this error?
Smaller versions of fastq files (and other files) are okay, as long as the error reproduces.

**Comment by dshinzie** [comment]
Hi @betsig! Sorry wish I saw this reply earlier. Here are some files I used to create the error above:

reads_1: `gs://sra-pub-src-4/SRR5204826/Farage_BI00923802_168h_rep1_R1.fastq.gz`
reads_2: `gs://sra-pub-src-8/SRR5204826/Farage_BI00923802_168h_rep1_R2.fastq.gz`
gtf: `gs://infer-strandedness/GRCh38.gtf` (Also accessible via https://storage.googleapis.com/infer-strandedness/GRCh38.gtf)
transcripts: `gs://infer-strandedness/GRCh38.fasta` (Also accessible via https://storage.googleapis.com/infer-strandedness/GRCh38.fasta)

The reads 1 and reads 2 fastq files are from a public bucket available to anyone. The gtf and transcripts files are in a bucket I made public that only has GRCh38 files.

I am able to create the error by downloading the files above locally and then running:

```
check_strandedness --gtf GRCh38.gtf --transcripts GRCh38.fasta --reads_1 Farage_BI00923802_168h_rep1_R1.fastq.gz --reads_2 Farage_BI00923802_168h_rep1_R2.fastq.gz
```

Or however you name the files after downloading.

Most recent attempt resulted in:

```
$ converting gtf to bed
$ Checking if fasta headers and bed file transcript_ids match...
$ Can't find transcript ids from GRCh38.fasta in stranded_test_Farage_BI00923802_168h_rep1_R1/GRCh38.bed
$ Trying to converting fasta header format to match transcript ids to the BED file...
$ Can't find any of the first 10 BED transcript_ids in fasta file... Check that these match
```

**Comment by dshinzie** [comment]
This line may be the source of my issue: `It also requires a transcriptome annotation (.fasta file - e.g. ensembl's .cdna.fasta, or a prebuilt kallisto index), and a corresponding gtf.` Our files are for genomes.

**Comment by dshinzie** [comment]
Yes, that was the issue. After using appropriate transcriptome files (from here: https://github.com/pachterlab/kallisto-transcriptome-indices/releases/tag/ensembl-96) including the kallisto index, I am almost able to get results:

```
$ Results stored in: stranded_test_Farage_BI00923802_168h_rep1_R1_3
$ converting gtf to bed
$ using transcriptome.idx as kallisto index
$ creating fastq files with first 200000 reads
$ quantifying with kallisto
$
$ [quant] fragment length distribution will be estimated from the data
$ [index] k-mer length: 31
$ [index] number of targets: 188,753
$ [index] number of k-mers: 109,544,288
$ [index] number of equivalence classes: 760,757
$ Warning: 37460 transcripts were defined in GTF file, but not in the index
$ [quant] running in paired-end mode
$ [quant] will process pair 1: stranded_test_Farage_BI00923802_168h_rep1_R1_3/Farage_BI00923802_168h_rep1_R1_sample.fq
$                              stranded_test_Farage_BI00923802_168h_rep1_R1_3/Farage_BI00923802_168h_rep1_R2_sample.fq
$ [quant] finding pseudoalignments for the reads ... done
$ [quant] processed 200,000 reads, 168,616 reads pseudoaligned
$ [quant] estimated average fragment length: 173.694
$ [   em] quantifying the abundances ... done
$ [   em] the Expectation-Maximization algorithm ran for 846 rounds
$ [  bam] writing pseudoalignments to BAM format .. done
$ [  bam] sorting BAM files .. done
$ [  bam] indexing BAM file .. done
$
$ checking strandedness
$ Reading reference gene model stranded_test_Farage_BI00923802_168h_rep1_R1_3/Homo_sapiens.GRCh38.96.bed ... Done
$ Loading SAM/BAM file ...  Total 200000 usable reads were sampled
$ Traceback (most recent call last):
$   File "/opt/conda/bin/check_strandedness", line 10, in <module>
$     sys.exit(main())
$   File "/opt/conda/lib/python3.9/site-packages/how_are_we_stranded_here/check_strandedness.py", line 185, in main
$     result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
$   File "/opt/conda/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
$     return func(*args, **kwargs)
$   File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
$     kwds_defaults = _refine_defaults_read(
$   File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1537, in _refine_defaults_read
$     raise ValueError(
$ ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
```

**Comment by dshinzie** [comment]
I was able to resolve the issue by forking the library and making this one change:

`result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\r\n", header=None, engine='python')`

```
$ Results stored in: stranded_test_Farage_BI00923802_168h_rep1_R1_3
$ converting gtf to bed
$ using transcriptome.idx as kallisto index
$ creating fastq files with first 200000 reads
$ quantifying with kallisto
$
$ [quant] fragment length distribution will be estimated from the data
$ [index] k-mer length: 31
$ [index] number of targets: 188,753
$ [index] number of k-mers: 109,544,288
$ [index] number of equivalence classes: 760,757
$ Warning: 37460 transcripts were defined in GTF file, but not in the index
$ [quant] running in paired-end mode
$ [quant] will process pair 1: stranded_test_Farage_BI00923802_168h_rep1_R1_3/Farage_BI00923802_168h_rep1_R1_sample.fq
$                              stranded_test_Farage_BI00923802_168h_rep1_R1_3/Farage_BI00923802_168h_rep1_R2_sample.fq
$ [quant] finding pseudoalignments for the reads ... done
$ [quant] processed 200,000 reads, 168,616 reads pseudoaligned
$ [quant] estimated average fragment length: 173.694
$ [   em] quantifying the abundances ... done
$ [   em] the Expectation-Maximization algorithm ran for 846 rounds
$ [  bam] writing pseudoalignments to BAM format .. done
$ [  bam] sorting BAM files .. done
$ [  bam] indexing BAM file .. done
$
$ checking strandedness
$ Reading reference gene model stranded_test_Farage_BI00923802_168h_rep1_R1_3/Homo_sapiens.GRCh38.96.bed ... Done
$ Loading SAM/BAM file ...  Total 200000 usable reads were sampled
$ This is PairEnd Data
$ Fraction of reads failed to determine: 0.1342
$ Fraction of reads explained by "1++,1--,2+-,2-+": 0.4335 (50.1% of explainable reads)
$ Fraction of reads explained by "1+-,1-+,2++,2--": 0.4324 (49.9% of explainable reads)
$ Under 60% of reads explained by one direction
$ Data is likely unstranded
```

I will submit a PR.

**Comment by dshinzie** [comment]
Looks like I can't submit a PR, but the change above is on line 185: https://github.com/betsig/how_are_we_stranded_here/blob/master/how_are_we_stranded_here/check_strandedness.py#L185

**Comment by betsig** [comment]
https://github.com/betsig/how_are_we_stranded_here/commit/617b2166f460445f93c5678863df53b6ffc3b798
Changed here.
