### ISSUE TITLE
not working with pyhton 3.9

### ISSUE THREAD

**Issue by robenimmersatt** [betsig/how_are_we_stranded_here#14]
Apparently python does not like the line `result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)` anymore.

Installing in a fresh conda env (with python 3.7) solved this.

Error message:

```
...
Reading reference gene model stranded_test_SRR3066196_1_val_1_1/gencode.v39.annotation.bed ... Done
Loading SAM/BAM file ...  Total 200000 usable reads were sampled
Results stored in: stranded_test_SRR3066196_1_val_1_1
converting gtf to bed
using kallisto_index as kallisto index
creating fastq files with first 200000 reads
quantifying with kallisto
checking strandedness
Traceback (most recent call last):
  File "~/miniconda3/envs/thesis/bin/check_strandedness", line 10, in <module>
    sys.exit(main())
  File "~/miniconda3/envs/thesis/lib/python3.9/site-packages/how_are_we_stranded_here/check_strandedness.py", line 185, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "~/miniconda3/envs/thesis/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "~/miniconda3/envs/thesis/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "~/miniconda3/envs/thesis/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1537, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
```

**Comment by bozbezbozzel** [comment]
getting the same with 3.10.

**Comment by rdistefano** [comment]
> getting the same with 3.10.

Got the same error and fixed it by replacing **\n** with **\t**. From:

`result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
`

to

`result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\t", header=None)`

**Comment by Rohit-Satyam** [comment]
@signalbash @aleighbrown I too got this error when creating a separate environment for the tool. Can you push such fixes to conda package as well?
