### ISSUE TITLE
Total 0 usable reads were sampled 

### ISSUE THREAD

**Issue by aleighbrown** [betsig/how_are_we_stranded_here#2]
Activate in a conda environment, no prebuilt kallisto index

ran using this command:

`check_strandedness --gtf /SAN/vyplab/vyplab_reference_genomes/annotation/human/GRCh38/gencode.v31.annotation.gtf --reads_1 /SAN/vyplab/alb_projects/data/ibm_geo/raw_data/SRR5888449_1.fastq --reads_2 /SAN/vyplab/alb_projects/data/ibm_geo/raw_data/SRR5888449_2.fastq --transcripts /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/gencode.v31.transcripts.fa`

Output:

```
Results stored in: stranded_test_SRR5888449_1
converting gtf to bed
generating kallisto index

[build] loading fasta file /SAN/vyplab/vyplab_reference_genomes/sequence/human/gencode/gencode.v31.transcripts.fa
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 1767 target sequences
[build] warning: replaced 4 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 1468053 contigs and contains 139801986 k-mers 

creating fastq files with first 200000 reads

gzip: stdin: not in gzip format

gzip: stdin: not in gzip format
quantifying with kallisto

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 226,882
[index] number of k-mers: 139,801,986
[index] number of equivalence classes: 960,759
Warning: 226882 transcripts were defined in GTF file, but not in the index
[quant] running in paired-end mode
[quant] will process pair 1: stranded_test_SRR5888449_1/SRR5888449_1_sample.fq
                             stranded_test_SRR5888449_1/SRR5888449_2_sample.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 0 reads, 0 reads pseudoaligned
[~warn] no reads pseudoaligned.
[quant] estimated average fragment length: 0
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 52 rounds
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. done

checking strandedness
Reading reference gene model stranded_test_SRR5888449_1/gencode.v31.annotation.bed ... Done
Loading SAM/BAM file ...  Finished
Total 0 usable reads were sampled
Unknown Data type
Traceback (most recent call last):
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/bin/check_strandedness", line 8, in <module>
    sys.exit(main())
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/lib/python3.7/site-packages/how_are_we_stranded_here/check_strandedness.py", line 142, in main
    print(result.iloc[i,0])
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/lib/python3.7/site-packages/pandas/core/indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/lib/python3.7/site-packages/pandas/core/indexing.py", line 2092, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/lib/python3.7/site-packages/pandas/core/indexing.py", line 235, in _has_valid_tuple
    self._validate_key(k, i)
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/lib/python3.7/site-packages/pandas/core/indexing.py", line 2014, in _validate_key
    self._validate_integer(key, axis)
  File "/SAN/vyplab/alb_projects/tools/.conda/envs/kallisto/lib/python3.7/site-packages/pandas/core/indexing.py", line 2088, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds`
```

**Comment by aleighbrown** [comment]
Solved by adding a check if the file is gzipped

**Comment by poflawless** [comment]
@aleighbrown   Hello, I faced with the same issue, you mean modify the check_strandedness.py script?
Thanks for your help
