### ISSUE TITLE
check_strandedness error with how_are_we_stranded_here

### ISSUE THREAD

**Issue by venkan** [betsig/how_are_we_stranded_here#6]
Hi, 

I tried using the tool like below but it is giving an ERROR:

Initially, I loaded the modules.

```
module load RSeQC/3.0.0-foss-2018b-Python-3.6.6
module load how_are_we_stranded_here/626c1ab-foss-2018b-Python-3.6.6
```

Then it started and gave the following Error:

```
check_strandedness --gtf /annotation_data/GRCh38/gencode.v27.annotation.gtf --transcripts gencode.v27.transcripts.fa --reads_1 sample10_R1.fastq.gz --reads_2 sample10_R2.fastq.gz

Results stored in: stranded_test_sample10_R1_6
converting gtf to bed
using kallisto_index as kallisto index
creating fastq files with first 200000 reads
quantifying with kallisto

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 200,401
[index] number of k-mers: 126,160,363
[index] number of equivalence classes: 825,248
Warning: 200401 transcripts were defined in GTF file, but not in the index
[quant] running in paired-end mode
[quant] will process pair 1: stranded_test_sample10_R1_6/sample10_R1_sample.fq
                             stranded_test_sample10_R1_6/sample10_R2_sample.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 2,182 reads, 1,064 reads pseudoaligned
[quant] estimated average fragment length: 180.624
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 574 rounds
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. done

checking strandedness
Reading reference gene model stranded_test_sample10_R1_6/gencode.v27.annotation.bed ... Done
Loading SAM/BAM file ...  Finished
Total 0 usable reads were sampled
Traceback (most recent call last):
  File "/apps/RSeQC/3.0.0-foss-2018b-Python-3.6.6/bin/infer_experiment.py", line 117, in <module>
    main()
  File "/apps/RSeQC/3.0.0-foss-2018b-Python-3.6.6/bin/infer_experiment.py", line 99, in main
    if other <0: other=0.0
TypeError: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/apps/how_are_we_stranded_here/626c1ab-foss-2018b-Python-3.6.6/bin/check_strandedness", line 11, in <module>
    load_entry_point('how-are-we-stranded-here==0+unknown', 'console_scripts', 'check_strandedness')()
  File "/apps/how_are_we_stranded_here/626c1ab-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/how_are_we_stranded_here/check_strandedness.py", line 151, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "/apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by betsig** [comment]
It looks like an issue with your kallisto index. 
`using kallisto_index as kallisto index`
in the messages means you already have an index prebuilt and named kallisto_index in the folder where you are running this. 
`Warning: 200401 transcripts were defined in GTF file, but not in the index`
This generally happens when you --transcripts fasta and --gtf GTF don't have the same transcript names. If you're using the Gencode annotations they should match...
I would try force rebuilding the index - either delete kallisto_index, or specify a different index name (-k) and it will build it for you.

**Comment by venkan** [comment]
> It looks like an issue with your kallisto index.
> `using kallisto_index as kallisto index`
> in the messages means you already have an index prebuilt and named kallisto_index in the folder where you are running this.
> `Warning: 200401 transcripts were defined in GTF file, but not in the index`
> This generally happens when you --transcripts fasta and --gtf GTF don't have the same transcript names. If you're using the Gencode annotations they should match...
> I would try force rebuilding the index - either delete kallisto_index, or specify a different index name (-k) and it will build it for you.

Now I don't see any problem with Kallisto index, but I still see the warning and other errors. Yes, I'm using the same version gencode annotation gtf and fasta files. Don't know why it is showing that warning.

```
check_strandedness --gtf gencode.v27.annotation.gtf --transcripts gencode.v27.transcripts.fa --reads_1 sample12_R1.fastq.gz --reads_2 sample12_R2.fastq.gz

Results stored in: stranded_test_sample12_R1
converting gtf to bed
generating kallisto index

[build] loading fasta file gencode.v27.transcripts.fa
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 1550 target sequences
[build] warning: replaced 4 non-ACGUT characters in the input sequence
        with pseudorandom nucleotides
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 1284693 contigs and contains 126160363 k-mers

creating fastq files with first 200000 reads
quantifying with kallisto

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 200,401
[index] number of k-mers: 126,160,363
[index] number of equivalence classes: 825,248
Warning: 200401 transcripts were defined in GTF file, but not in the index
[quant] running in paired-end mode
[quant] will process pair 1: stranded_test_sample12_R1/sample12_R1_sample.fq
                                          stranded_test_sample12_R1/sample12_R2_sample.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 1,783 reads, 812 reads pseudoaligned
[quant] estimated average fragment length: 171.096
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 448 rounds
[  bam] writing pseudoalignments to BAM format .. done
[  bam] sorting BAM files .. done
[  bam] indexing BAM file .. done

checking strandedness
Reading reference gene model stranded_test_sample12_R1/gencode.v27.annotation.bed ... Done
Loading SAM/BAM file ...  Finished
Total 0 usable reads were sampled
Traceback (most recent call last):
  File "apps/RSeQC/3.0.0-foss-2018b-Python-3.6.6/bin/infer_experiment.py", line 117, in <module>
    main()
  File "apps/RSeQC/3.0.0-foss-2018b-Python-3.6.6/bin/infer_experiment.py", line 99, in main
    if other <0: other=0.0
TypeError: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "apps/how_are_we_stranded_here/626c1ab-foss-2018b-Python-3.6.6/bin/check_strandedness", line 11, in <module>
    load_entry_point('how-are-we-stranded-here==0+unknown', 'console_scripts', 'check_strandedness')()
  File "apps/how_are_we_stranded_here/626c1ab-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/how_are_we_stranded_here/check_strandedness.py", line 151, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "apps/Python/3.6.6-foss-2018b/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by betsig** [comment]
Okay... maybe not then

The other thing that raises flags to me is

> [quant] processed 1,783 reads, 812 reads pseudoaligned

which eventually causes

> Total 0 usable reads were sampled


You're using 200,000 reads from your fastqs and only managing to process ~1% of them. I've seen this happen in some lower quality sequencing. Have you checked that the quality is okay (fastqc) and that you don't have any major contamination (genomic or small RNA from any species - including human, or transcriptomic from any species)

**Comment by venkan** [comment]
> Okay... maybe not then
> 
> The other thing that raises flags to me is
> 
> > [quant] processed 1,783 reads, 812 reads pseudoaligned
> 
> which eventually causes
> 
> > Total 0 usable reads were sampled
> 
> You're using 200,000 reads from your fastqs and only managing to process ~1% of them. I've seen this happen in some lower quality sequencing. Have you checked that the quality is okay (fastqc) and that you don't have any major contamination (genomic or small RNA from any species - including human, or transcriptomic from any species)

In fact, I tried this on multiple datasets...and I still get the same Error.

**Comment by betsig** [comment]
Can you send me a subset of the data you were getting the error with?

**Comment by venkan** [comment]
> Can you send me a subset of the data you were getting the error with?

Yes, Please check the attachments.
[Archive.zip](https://github.com/betsig/how_are_we_stranded_here/files/5404048/Archive.zip)

**Comment by betsig** [comment]
Sorry for taking so long... 
It was an issue with how gencode formats their transcripts.fa file. 
e.g.
>ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript|
There's no space after the transcript id, which screws up matching to the gtf "transcript_id" column / bed ID. 
The latest release solves this problem by patching the fasta file temporarily when generating the kallisto index. You may need to generate a new index for this to work.

**Comment by alex-wenzel** [comment]
I believe I am experiencing this issue as well using the M26 (GRCm39) release from Gencode. I confirmed that I installed v1.0.1 from Pip this afternoon and based on the output, it looks like my run triggered the new code that was added in the release ([link directly to line of code that prints](https://github.com/betsig/how_are_we_stranded_here/commit/0b77cc28dfccd986b8a4da0901e2e0e1a46bcfbc#diff-672bbf90d80ce042a20679ee2d764d060e44c1737098fffcaeb0b865181c2a75R127)). 

```
$ pip freeze | grep stranded

how-are-we-stranded-here==1.0.1 
```

```
$ check_strandedness --gtf ../gencode_m26_GRCm39/gencode.vM26.annotation.gtf --transcripts ../gencode_m26_GRCm39/gencode.vM26.transcripts.fa --reads_1 1_KPC46-PT_Org-1_S63_L002_R1_001.fastq.gz --reads_2 1_KPC46-PT_Org-1_S63_L002_R2_001.fastq.gz 

Results stored in: stranded_test_1_KPC46-PT_Org-1_S63_L002_R1_001
converting gtf to bed
Checking if fasta headers and bed file transcript_ids match...
Can't find transcript ids from ../gencode_m26_GRCm39/gencode.vM26.transcripts.fa in stranded_test_1_KPC46-PT_Org-1_S63_L002_R1_001/gencode.vM26.annotation.bed
Trying to converting fasta header format to match transcript ids to the BED file...
generating kallisto index

[build] loading fasta file stranded_test_1_KPC46-PT_Org-1_S63_L002_R1_001/transcripts.fa
[build] k-mer length: 31
[build] warning: clipped off poly-A tail (longer than 10)
        from 757 target sequences
[build] counting k-mers ... done.
[build] building target de Bruijn graph ...  done 
[build] creating equivalence classes ...  done
[build] target de Bruijn graph has 865656 contigs and contains 120547711 k-mers 

creating fastq files with first 200000 reads
quantifying with kallisto

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 140,670
[index] number of k-mers: 120,547,711
[index] number of equivalence classes: 508,846
[quant] running in paired-end mode
[quant] will process pair 1: stranded_test_1_KPC46-PT_Org-1_S63_L002_R1_001/1_KPC46-PT_Org-1_S63_L002_R1_001_sample.fq
                             stranded_test_1_KPC46-PT_Org-1_S63_L002_R1_001/1_KPC46-PT_Org-1_S63_L002_R2_001_sample.fq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 200,000 reads, 104,629 reads pseudoaligned
[quant] estimated average fragment length: 188.124
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 785 rounds
[  bam] writing pseudoalignments to BAM format .. checking strandedness


stranded_test_1_KPC46-PT_Org-1_S63_L002_R1_001/kallisto_strand_test/pseudoalignments.bam does NOT exists.

Traceback (most recent call last):
  File "/Users/alexwenzel/miniconda3/bin/check_strandedness", line 11, in <module>
    sys.exit(main())
  File "/Users/alexwenzel/miniconda3/lib/python3.7/site-packages/how_are_we_stranded_here/check_strandedness.py", line 185, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "/Users/alexwenzel/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/alexwenzel/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/alexwenzel/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/Users/alexwenzel/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/alexwenzel/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

If I look at the line `[  bam] writing pseudoalignments to BAM format .. checking strandedness` and compare it to venkan's output above, it almost looks as if Kallisto got cut off silently while writing a bam file. I can look for similar issues in the Kallisto repo in the meantime, but since this results in the same original error and appears to be triggering the new code, I thought it warranted a post in this issue as well.
